#deployment part
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: honlee_ftps
        imagePullPolicy: Never
        ports:
          - containerPort: 21
          - containerPort: 30021
---
#Service part
apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared"
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100  #아이피 주소 잡아줌.
  ports:
    - port: 21    #연결을 수립하고 요청을 주고받는 포트
      name: ftps
      targetPort: 21
      protocol: TCP
    - port: 30021     #실제 데이터가 오고가는 포트
      name: ftps-pasv
      targetPort: 30021
      protocol: TCP