apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx       #디플로이먼트 이름
  labels:
    app: nginx
spec:
# replicas: 1       #1개의 파드 복제본 (레플리카) 를 만든다.
  selector:
    matchLabels:
      app: nginx      #서비스가 찾아낼때 이름
  strategy:            # pod 교체 전략, 따로 입력 안해주면 기본 rollingUpdate 전략이 됨.
    rollingUpdate:        # 파드를 하나씩 죽이고 새로띄우면서 순차적으로 교체하는 방법
      maxSurge: 25%         # 롤링 업데이트시 동시에 생성될 수 있는 파드의 최대 개수
      maxUnavailable: 25%   # 롤링 업데이트시 동시에 삭제 할 수 있는 파드의 최대 개수
    type: RollingUpdate     # 대충 롤링업데이트 전략이라는 뜻~
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: honlee_nginx    #이미 빌드된 도커이미지 이름
        imagePullPolicy: Never  #없어도 어디서 땡기지않음
        name: nginx           #파드이름 ..?
        ports:
        - containerPort: 80
        - containerPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared" #80포트, 443포트 모두 하나의 아이피로 쓸수있도록해줌
  labels:
    app: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100  #아이피 주소 잡아줌.
  selector:
    app: nginx    #서비스가 파드를 찾아갈때 쓸 이름
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443